/*
 * adminhomepage.java
 *
 * Created on November 17, 2022, 9:41 PM
 */

package mypackages;

/**
 *
 * @author  Dr. Sabin
 */
public class adminhomepage extends javax.swing.JFrame {

    /** Creates new form adminhomepage */
    public adminhomepage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        managebook = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 33));
        jLabel2.setText("welcome to admin page");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jButton1.setText("RETURN BOOK");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 160, 40));

        jButton2.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jButton2.setText("HOME");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        managebook.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        managebook.setText("MANAGE BOOKS");
        managebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managebookMouseClicked(evt);
            }
        });
        managebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managebookActionPerformed(evt);
            }
        });
        jPanel2.add(managebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 190, 40));

        jButton4.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jButton4.setText("MANAGE STUDENTS");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 220, 40));

        jButton5.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jButton5.setText("ISUE BOOK");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 130, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1040, 110));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 470));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void managebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managebookActionPerformed
// TODO add your handling code here:

    
}//GEN-LAST:event_managebookActionPerformed

private void managebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managebookMouseClicked
// TODO add your handling code here:
      bookmanagement obj=new bookmanagement ();
      obj.show();
      dispose();
    
}//GEN-LAST:event_managebookMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminhomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton managebook;
    // End of variables declaration//GEN-END:variables

}
