/*
 * bookmanagement.java
 *
 * Created on November 21, 2022, 10:15 AM
 */

package mypackages;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author  Dr. Sabin
 */
public class bookmanagement extends javax.swing.JFrame {

    /** Creates new form bookmanagement */
    String bookID,BookName,authr;
    int qnty;
    DefaultTableModel model;
    public bookmanagement() {
        initComponents();
        displayDataintable();
    }
    
 //method to automatically display data in table from database   
  public void displayDataintable(){
  try{
      Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection)
    DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root","" ); 
     String sql="Select * from Librarybooks";
    PreparedStatement pst=(PreparedStatement) con.prepareStatement(sql); 
    ResultSet rs=pst.executeQuery();
    
    while(rs.next()){
    String bkID=rs.getString("book_ID");
    String bkName=rs.getString("Book_name");
    String bkauthor=rs.getString("author");
    String qty=rs.getString("quantity");
    
   Object[] obj={bkID,bkName,bkauthor,qty};
   model =(DefaultTableModel) bktable.getModel();
  model.addRow(obj);
    }
  }
  catch(Exception e){
  e.printStackTrace();
  }
  
  }
  //clearing data in table to avoid duplication after inserting new data or deleting data
  public void cleartable(){
  
      DefaultTableModel model=(DefaultTableModel) bktable.getModel();
      model.setRowCount(0);
  
  }

  //method to update data recorded
  public void updatedata(){
  boolean isupdated=false;
   bookID=book_ID.getText();
     BookName=Book_name.getText();
     authr=author.getText();
     qnty=Integer.parseInt(quantity.getText());
  }
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        book_ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Book_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addbook = new javax.swing.JButton();
        author = new javax.swing.JTextField();
        addbook1 = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bktable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        managebook = new javax.swing.JButton();
        jhome = new javax.swing.JButton();
        jview = new javax.swing.JButton();
        mngtud = new javax.swing.JButton();
        jreturn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel1.setText("MANAGE BOOKS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 280, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Book ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 40));

        book_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_IDActionPerformed(evt);
            }
        });
        jPanel1.add(book_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 260, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("Book name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 40));

        Book_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_nameActionPerformed(evt);
            }
        });
        jPanel1.add(Book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 260, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Author");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 40));

        addbook.setFont(new java.awt.Font("Tahoma", 1, 18));
        addbook.setText("UPDATE BOOK");
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });
        jPanel1.add(addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 170, 40));

        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 260, 30));

        addbook1.setFont(new java.awt.Font("Tahoma", 1, 18));
        addbook1.setText("Add Book");
        addbook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbook1ActionPerformed(evt);
            }
        });
        jPanel1.add(addbook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 170, 40));

        remove.setFont(new java.awt.Font("Tahoma", 1, 18));
        remove.setText("DELETE BOOK");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 170, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 80, 30));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 260, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dr. Sabin\\Downloads\\Tired man from work (5).gif")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 560, 580));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 690));

        bktable.setFont(new java.awt.Font("Tahoma", 1, 14));
        bktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID ", "Book Title", "author", "quantity"
            }
        ));
        bktable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bktableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bktable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 640, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 740, 580));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managebook.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        managebook.setText("MANAGE BOOKS");
        managebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managebookMouseClicked(evt);
            }
        });
        managebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managebookActionPerformed(evt);
            }
        });
        jPanel4.add(managebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 190, 40));

        jhome.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jhome.setText("HOME");
        jhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhomeActionPerformed(evt);
            }
        });
        jPanel4.add(jhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 40));

        jview.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jview.setText("VIEW RECORDS");
        jview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jviewActionPerformed(evt);
            }
        });
        jPanel4.add(jview, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 170, 40));

        mngtud.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        mngtud.setText("MANAGE STUDENTS");
        mngtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngtudActionPerformed(evt);
            }
        });
        jPanel4.add(mngtud, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 220, 40));

        jreturn.setFont(new java.awt.Font("Footlight MT Light", 1, 18));
        jreturn.setText("RETURN BOOK");
        jPanel4.add(jreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 160, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 28));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, -1, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void book_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_IDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_book_IDActionPerformed

private void Book_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_nameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Book_nameActionPerformed

private void addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_addbookActionPerformed

private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_authorActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jButton1ActionPerformed

private void addbook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbook1ActionPerformed
//adding book to the database
     try{ 
        
       
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection)
    DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root","" ); 
     String Querry="insert into librarybooks(book_ID,Book_name,author,quantity) values(?,?,?,?)";
    PreparedStatement pst=(PreparedStatement) con.prepareStatement(Querry); 
    if(book_ID.getText().equals("")){
              JOptionPane.showMessageDialog(null, "book-id must be filled");
         }
   else if(Book_name.getText().equals("")){
        JOptionPane.showMessageDialog(null, "book name must be filled");
    } else if(author.getText().equals("")){
        JOptionPane.showMessageDialog(null, "author name must be filled");
    }
     
     else if(quantity.getText().equals("")){
        JOptionPane.showMessageDialog(null, "quantity must be filled");
    }
    
   
    
    else{
    pst.setString(1,book_ID.getText()); 
    pst.setString(2,Book_name.getText());
    pst.setString(3,author.getText());
    pst.setString(4,quantity.getText());
   pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "book added successfully!!!"); 
    
     book_ID.setText(null);
     Book_name.setText(null);
     author.setText(null);
     quantity.setText(null);
     
    cleartable();
     displayDataintable();
      
       
    }
   
    }   
    catch(Exception e){    
    JOptionPane.showMessageDialog(null, e); 
        
    }
   
     
                                       
 
}//GEN-LAST:event_addbook1ActionPerformed

private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
// TODO add your handling code here:
           try{ 
        
       
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection)
    DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root","" ); 
    String Querry="DELETE FROM `librarybooks` WHERE `books`.`book_ID` = ?";
    PreparedStatement pst=(PreparedStatement) con.prepareStatement(Querry); 
    if(book_ID.getText().equals("")){
              JOptionPane.showMessageDialog(null, "BOOK-ID must be filled");
         } 
        else{
    pst.setString(1,book_ID.getText()); 
   /* pst.setString(2,Book_name.getText());
    pst.setString(3,author.getText());*/  
   pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "deleted!"); 
     book_ID.setText(null);
     Book_name.setText(null);
     author.setText(null);
      quantity.setText(null);
      
  cleartable();
     displayDataintable();
        
    }
    }   
    catch(Exception e){    
        JOptionPane.showMessageDialog(null, e); 
        
    }
   
    
    
}//GEN-LAST:event_removeActionPerformed

private void managebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managebookMouseClicked
// TODO add your handling code here:
      bookmanagement obj=new bookmanagement ();
      obj.show();
      dispose();
}//GEN-LAST:event_managebookMouseClicked

private void managebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managebookActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_managebookActionPerformed

private void jviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jviewActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jviewActionPerformed

private void jhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhomeActionPerformed
// TODO add your handling code here:
    adminhomepage obj=new adminhomepage();
    obj.show();
    dispose();
}//GEN-LAST:event_jhomeActionPerformed

private void mngtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngtudActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_mngtudActionPerformed

private void bktableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bktableMouseClicked
// TODO add your handling code here:
    int rownum=bktable.getSelectedRow();
    TableModel model=bktable.getModel();
    book_ID.setText(model.getValueAt(rownum,0).toString());
    Book_name.setText(model.getValueAt(rownum,1).toString());
    author.setText(model.getValueAt(rownum,2).toString());
    quantity.setText(model.getValueAt(rownum,3).toString());
    
    
    
}//GEN-LAST:event_bktableMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookmanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Book_name;
    private javax.swing.JButton addbook;
    private javax.swing.JButton addbook1;
    private javax.swing.JTextField author;
    private javax.swing.JTable bktable;
    private javax.swing.JTextField book_ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jhome;
    private javax.swing.JButton jreturn;
    private javax.swing.JButton jview;
    private javax.swing.JButton managebook;
    private javax.swing.JButton mngtud;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables

}
